---
version: '3.4'

networks:
    retrieval:

services:
    weaviate:
        command:
            - --host
            - 0.0.0.0
            - --port
            - '8080'
            - --scheme
            - http
        image: semitechnologies/weaviate:1.18.0
        restart: on-failure:0
        environment:
            QUERY_DEFAULTS_LIMIT: 25
            AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
            PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
            DEFAULT_VECTORIZER_MODULE: 'none'
            ENABLE_MODULES: ''
            CLUSTER_HOSTNAME: 'node1'
        networks:
            retrieval:
                aliases:
                    - weviate.scratch.co
        volumes:
            - weaviate-data1:/var/lib/weaviate

    backend-retrieval:
        build:
            context: '..'
            dockerfile: 'docker/Dockerfile'
            target: 'localdev'
        networks:
            - retrieval
        environment:
            DATASTORE: "weaviate"
            WEAVIATE_HOST: "http://weviate.scratch.co"
            WEAVIATE_PORT: "8080"
            WEAVIATE_INDEX: "OpenAIDocument"
        image: 'siyavula/retrieval:working'
        volumes:
            - "../src:/var/task/src"

volumes:
  weaviate-data1:
...